apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ba-demo-app
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/salimbouch/demo.git
    targetRevision: HEAD
    path: k8s
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true