version: '3'
services:
  selenium-hub:
    image: selenium/hub:4.9.0
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:4.9.0
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  firefox:
    image: selenium/node-firefox:4.9.0
    shm_size: 2gb
    depends_on:
      - selenium-hub
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443

  web-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - selenium-hub
      - chrome
      - firefox
      - web-app