apiVersion: batch/v1
kind: Job
metadata:
  name: selenium-test-${JOB_SUFFIX}
spec:
  template:
    metadata:
      name: selenium-test-${JOB_SUFFIX}
    spec:
      containers:
        - name: test
          image: ${DOCKERHUB_USERNAME}/k8s-selenium:test-${IMAGE_TAG}
          imagePullPolicy: Always
          env:
            - name: HUB_URL
              value: "http://selenium-hub:4444/wd/hub"
            - name: APP_URL
              value: "http://web-app:8080"
      restartPolicy: Never
  backoffLimit: 4