apiVersion: batch/v1
kind: Job
metadata:
  name: selenium-test
spec:
  template:
    metadata:
      name: selenium-test
    spec:
      containers:
        - name: test
          image: salimbou/k8s-selenium:test-bdecfc29518c28eb7cbdc63f65e556e0f404690f
          imagePullPolicy: Always
          env:
            - name: HUB_URL
              value: "http://selenium-hub:4444/wd/hub"
            - name: APP_URL
              value: "http://web-app:8080"
      restartPolicy: Never
  backoffLimit: 4