apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: edge-node-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: edge-node
  minReplicas: 1
  maxReplicas: 10
  targetCPUUtilizationPercentage: 70