apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app
          image: salimbou/k8s-selenium:web-app-606eb67b56105ffd9bb02ac8741219f0c63df783
          imagePullPolicy: Always
          ports:
            - containerPort: 8080