apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app
          image: salimbou/k8s-selenium:web-app-54cb413f87eb1c1569fdcd77aaea5c256d40f0a2
          imagePullPolicy: Always
          ports:
            - containerPort: 8080