- name: Run and Monitor Selenium Test Job
  id: selenium-test
  run: |
    # Apply the job
    cat k8s/jobs/selenium-test-job.yaml | \
    sed "s|\${DOCKER_USERNAME}|${{ secrets.DOCKERHUB_USERNAME }}|g; s|\${IMAGE_TAG}|${{ env.IMAGE_TAG }}|g" | \
    kubectl apply -f -

    echo "Waiting for pod to be ready..."
    kubectl wait --for=condition=ready pod -l job-name=selenium-test-job --timeout=300s

    # Function to check job status
    check_job_status() {
      kubectl get job selenium-test-job -o jsonpath='{.status.conditions[].type}'
    }

    # Stream logs and monitor job status
    timeout 600s bash << 'EOF'
      kubectl logs -f job/selenium-test-job &
      log_pid=$!

      while true; do
        status=$(check_job_status)
        if [[ $status == "Complete" ]]; then
          echo "Job completed successfully"
          kill $log_pid
          exit 0
        elif [[ $status == "Failed" ]]; then
          echo "Job failed"
          kill $log_pid
          exit 1
        fi
        sleep 5
      done
    EOF

    # Capture the exit status
    exit_status=$?

    # Save logs to a file
    kubectl logs job/selenium-test-job > test-results.log

    # Set output variable for use in subsequent steps
    if [ $exit_status -eq 0 ]; then
      echo "status=success" >> $GITHUB_OUTPUT
    elif [ $exit_status -eq 124 ]; then
      echo "status=timeout" >> $GITHUB_OUTPUT
    else
      echo "status=failure" >> $GITHUB_OUTPUT
    fi

    # Print final status
    if [ $exit_status -eq 0 ]; then
      echo "Selenium tests completed successfully"
    elif [ $exit_status -eq 124 ]; then
      echo "Selenium tests timed out"
    else
      echo "Selenium tests failed"
    fi

    # Exit with the appropriate status
    exit $exit_status

- name: Upload test results
  uses: actions/upload-artifact@v3
  if: always()
  with:
    name: test-results
    path: test-results.log

- name: Clean up test job
  if: always()
  run: kubectl delete job selenium-test-job --ignore-not-found

- name: Check Selenium test status
  if: steps.selenium-test.outputs.status != 'success'
  run: |
    if [[ "${{ steps.selenium-test.outputs.status }}" == "failure" ]]; then
      echo "Selenium tests failed"
    else
      echo "Selenium tests timed out"
    fi
    exit 1