name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.sha }}
      DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven (skip tests)
        run: mvn clean package -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Web App Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/k8s-selenium:web-app-${{ env.IMAGE_TAG }}

      - name: Build and push Test Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.test
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/k8s-selenium:test-${{ env.IMAGE_TAG }}

      - name: Set up Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > $HOME/.kube/config

      - name: Update Kubernetes deployment with new image
        run: |
          kubectl set image deployment/web-app web-app=${{ secrets.DOCKERHUB_USERNAME }}/k8s-selenium:web-app-${{ env.IMAGE_TAG }}
          kubectl rollout status deployment/web-app

      - name: Delete old test job if exists
        run: kubectl delete job selenium-test-job --ignore-not-found

      - name: Create and run Selenium test job
        run: |
          cat k8s/selenium-test-job.yaml | \
          sed "s|\${DOCKER_USERNAME}|${{ secrets.DOCKERHUB_USERNAME }}|g; s|\${IMAGE_TAG}|${{ env.IMAGE_TAG }}|g" | \
          kubectl apply -f -

      - name: Wait for job completion and get logs
        run: |
          kubectl wait --for=condition=complete job/selenium-test-job --timeout=300s || \
          kubectl wait --for=condition=failed job/selenium-test-job --timeout=10s
          kubectl logs job/selenium-test-job > test-results.log

      - name: Check job status and fail if necessary
        run: |
          if kubectl get job selenium-test-job -o jsonpath='{.status.conditions[?(@.type=="Failed")].status}' | grep -q True; then
            echo "Selenium tests failed"
            exit 1
          fi

      - name: Upload test results
        uses: actions/upload-artifact@v3
        if: always()
        with:
          name: test-results
          path: test-results.log

      - name: Clean up test job
        if: always()
        run: kubectl delete job selenium-test-job --ignore-not-found