name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven
        run: mvn clean package -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Web App Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/k8s-selenium:web-app-${{ github.sha }}

      - name: Build and push Test Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.test
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/k8s-selenium:test-${{ github.sha }}

      - name: Generate Job Suffix
        id: generate_suffix
        run: echo "JOB_SUFFIX=$(date +%s%N | sha256sum | head -c6)" >> $GITHUB_OUTPUT

      - name: Deploy to k3s
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
          JOB_SUFFIX: ${{ steps.generate_suffix.outputs.JOB_SUFFIX }}
        run: |
          echo "$KUBE_CONFIG" | base64 -d > kubeconfig
          
          # Update web-app deployment
          sed -i 's|image: .*|image: ${{ secrets.DOCKERHUB_USERNAME }}/k8s-selenium:web-app-${{ github.sha }}|' k8s/deployments/web-app-deployment.yaml
          kubectl --kubeconfig=./kubeconfig apply -f k8s/deployments/
          kubectl --kubeconfig=./kubeconfig apply -f k8s/services/

          # Create and apply Selenium test job
          cat k8s/jobs/selenium-test-job.yaml | sed \
            -e "s/\${JOB_SUFFIX}/$JOB_SUFFIX/g" \
            -e 's|${DOCKERHUB_USERNAME}|${{ secrets.DOCKERHUB_USERNAME }}|g' \
            -e 's|${IMAGE_TAG}|${{ github.sha }}|g' \
            | kubectl --kubeconfig=./kubeconfig apply -f -

      - name: Run Selenium tests
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
          JOB_SUFFIX: ${{ steps.generate_suffix.outputs.JOB_SUFFIX }}
        run: |
          kubectl --kubeconfig=./kubeconfig wait --for=condition=complete job/selenium-test-${JOB_SUFFIX} --timeout=600s
          TEST_POD=$(kubectl --kubeconfig=./kubeconfig get pods --selector=job-name=selenium-test-${JOB_SUFFIX} --output=jsonpath='{.items[*].metadata.name}')
          kubectl --kubeconfig=./kubeconfig logs $TEST_POD > test_results.log
          if grep -q "FAILED" test_results.log; then exit 1; fi

      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: test_results.log

      - name: Cleanup
        if: always()
        env:
          KUBE_CONFIG: ${{ secrets.KUBE_CONFIG }}
          JOB_SUFFIX: ${{ steps.generate_suffix.outputs.JOB_SUFFIX }}
        run: |
          kubectl --kubeconfig=./kubeconfig delete job selenium-test-${JOB_SUFFIX}