name: CI/CD Pipeline for Web App with Selenium Tests

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}  # Use the DockerHub username from GitHub secrets
      IMAGE_TAG: ${{ github.sha }}  # Use the commit SHA as the image tag

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Build with Maven (no tests)
        run: mvn clean package -DskipTests

      - name: Log in to DockerHub
        run: echo "${{ secrets.DOCKER_TOKEN }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKER_USERNAME }}/k8s-selenium:${{ github.sha }} .

      - name: Push Docker image to DockerHub
        run: docker push ${{ secrets.DOCKER_USERNAME }}/k8s-selenium:${{ github.sha }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.27.0'  # Ensure you're using a compatible version

      - name: Set up K8s context
        run: echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      - name: Update Kubernetes deployment with new image
        run: |
          kubectl set image deployment/web-app web-app=${{ secrets.DOCKER_USERNAME }}/k8s-selenium:${{ github.sha }}

  run-selenium-tests:
    runs-on: ubuntu-latest
    needs: build-and-deploy  # Ensure the deployment is completed before running tests
    env:
      HUB_URL: http://selenium-hub:4444/wd/hub  # Ensure this points to the correct Selenium hub
      APP_URL: http://web-app:8080  # Kubernetes web app service URL

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Java 17
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Run Selenium Tests in Parallel
        run: mvn clean test -DsuiteXmlFile=testng.xml
