name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: web-app-${{ github.sha }}  # Tag with the commit SHA
      DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven (skip tests)
        run: mvn clean package -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Web App Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/k8s-selenium:${{ env.IMAGE_TAG }}

      - name: Set up kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'v1.27.0'  # Adjust if needed

      - name: Configure K8s context
        run: echo "${{ secrets.KUBECONFIG }}" > $HOME/.kube/config

      - name: Update Kubernetes deployment with new image
        run: |
          kubectl set image deployment/web-app web-app=${{ secrets.DOCKERHUB_USERNAME }}/k8s-selenium:${{ env.IMAGE_TAG }}

  run-selenium-tests:
    runs-on: ubuntu-latest
    needs: build-and-deploy  # Ensures that the build and deploy job finishes first
    env:
      HUB_URL: http://selenium-hub:4444/wd/hub  # Selenium Hub URL in Kubernetes cluster
      APP_URL: http://web-app:8080  # Web app service URL
      DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Run Selenium Tests in Parallel
        run: mvn clean test -DsuiteXmlFile=testng.xml
