name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    env:
      IMAGE_TAG: ${{ github.sha }}
      DOCKER_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Build with Maven (skip tests)
        run: mvn clean package -DskipTests

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Web App Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/k8s-selenium:web-app-${{ env.IMAGE_TAG }}

      - name: Build and push Test Docker image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./docker/Dockerfile.test
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/k8s-selenium:test-${{ env.IMAGE_TAG }}

      - name: Set up Kubeconfig
        run: |
          mkdir -p $HOME/.kube
          echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > $HOME/.kube/config
          chmod 600 $HOME/.kube/config

      - name: Update Kubernetes deployment with new image
        run: |
          kubectl set image deployment/web-app web-app=${{ secrets.DOCKERHUB_USERNAME }}/k8s-selenium:web-app-${{ env.IMAGE_TAG }}
          kubectl rollout status deployment/web-app

      - name: Delete old test job if exists
        run: kubectl delete job selenium-test-job --ignore-not-found

      - name: Run and Monitor Selenium Test Job
        run: |
          # Apply the job
          cat k8s/jobs/selenium-test-job.yaml | \
          sed "s|\${DOCKER_USERNAME}|${{ secrets.DOCKERHUB_USERNAME }}|g; s|\${IMAGE_TAG}|${{ env.IMAGE_TAG }}|g" | \
          kubectl apply -f -

          # Monitor job status
          start_time=$(date +%s)
          while true; do
            status=$(kubectl get job selenium-test-job -o jsonpath='{.status.conditions[].type}')
            if [[ $status == "Complete" ]]; then
              echo "Selenium tests completed successfully"
              kubectl logs job/selenium-test-job
              exit 0
            elif [[ $status == "Failed" ]]; then
              echo "Selenium tests failed"
              kubectl logs job/selenium-test-job
              exit 1
            fi
          
            current_time=$(date +%s)
            elapsed=$((current_time - start_time))
            if [[ $elapsed -ge 300 ]]; then
              echo "Selenium tests timed out after 300 seconds"
              kubectl logs job/selenium-test-job
              exit 2
            fi
          
            sleep 5
          done

      - name: Upload test logs
        if: always()
        uses: actions/upload-artifact@v3
        with:
          name: test-logs
          path: |
            kubectl logs job/selenium-test-job > test-logs.txt

      - name: Clean up test job
        if: always()
        run: kubectl delete job selenium-test-job --ignore-not-found